server:
  servlet:
    context-path: "/api/v1.0/mongo"

mongo:
  url: "mongodb+srv://dev:Normandy19@cluster0.oykwp.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  isRemote: true
  collection:
    databaseName: "GameDB"
    collectionName: "GamesCollection"