server:
  servlet:
    context-path: "/api/v1.0/mongo"

mongo:
  url: "mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false"
  isRemote: false
  collection:
    databaseName: "MyGameLibrary"
    collectionName: "Games"