server:
  servlet:
    context-path: "/api/v1.0/mongo"

mongo:
  isRemote: false
  url: "mongodb+srv://dev-1:Normandy19@cluster0.feijx.mongodb.net/MyGameLibraryApp?retryWrites=true&w=majority"
  collection:
    databaseName: "MyGameLibraryApp"
    collectionName: "gameCollection"