server:
  servlet:
    context-path: "/api/v1.0/mongo"

spring:
  datasource:
    url: &dbURL jdbc:sqlserver://gamelibraryapp.database.windows.net:1433;database=test_db;user=lionheart@gamelibraryapp;password=Normandy19;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: &dbUser lionheart
    password: &dbPassword Normandy19
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update